# Generated by Django 4.0 on 2022-01-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
